# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vel0HMQErADThl5F5jPNz4nhaTiXh5tl
"""

import pandas as pd
baza={
    "FISH":[ "Qadamova Z.E", "Xalilov D.A", "Djalilov M.L", "Abduvaliyev I.O", "Jo'rayeva G.F", "Jo'rayeva G.F", "Turdimatov M.M", "Arabboyev A.A" ],
    "Fan nomi":[ "Sun'iy intellekt", "Sun'iy intellekt", "Kompyuterni tashkil etish", "Kompyuterni tashkil etish", "Elektronika va sxemalar", "Elektronika va sxemalar", "Kiberxavfsizlik asoslari", "Kiberxavfsizlik asoslari" ],
    "Mashg'ulot turi":[ "amaliy", "ma'ruza", "ma'ruza", "amaliy", "amaliy", "ma'ruza", "ma'ruza", "amaliy" ],
    "Kafedrasi":[ "Axborot texnologiyalari", "Axborot texnologiyalari", "Axborot texnologiyalari", "Axborot texnologiyalari", "Tabiiy fanlar", "Tabiiy fanlar", "Axborot texnologiyalari", "Axborot texnologiyalari" ],



}
db=pd.DataFrame(baza)
print(db)

from google.colab import drive
drive.mount('/content/drive')

db.to_excel("o'qituvchilar.xlsx")